### ISSUE TITLE
Сделать данные классов в паттерне "Стратегия" приватными

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#1]
- [x] Члены-данные класса являются частью деталей реализации. Как правило, их следует объявлять приватным, чтобы только сам класс имел к ним доступ. Если наследники будут иметь доступ к protected-данным родителя, то изменение родительского класса может повлечь необходимость изменения дочерних классов.

**Comment by ViacheslavTarasov** [comment]
Исправил

**Comment by alexey-malov** [comment]
ok
