### ISSUE TITLE
В интерфейсе OutputDataStreamInterface недостаточно информации о типах параметров

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#10]
- [x] Следует задать тип для параметра $data

- [x] В классах, реализующих этот интерфейс также нужно задать тип параметра data

**Comment by ViacheslavTarasov** [comment]
Указал недостающие типы

**Comment by alexey-malov** [comment]
- [ ] Для метода writeByte(string $data) не указаны типы аргумента в классах, реализующих этот интерфейс

**Comment by ViacheslavTarasov** [comment]
Теперь везде добавил
