### ISSUE TITLE
Замечания по тестам к 3 лабе

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#13]
```php
        $this->assertEquals(4, strlen($this->outputStream->getData()));
        $this->assertEquals('1', unpack('C', $this->outputStream->getData()[0])[1]);
        $this->assertEquals(self::TEST_TEXT[0], unpack('a', $this->outputStream->getData()[1])[1]);
        $this->assertEquals('6', unpack('C', $this->outputStream->getData()[2])[1]);
        $this->assertEquals(self::TEST_TEXT[1], unpack('a', $this->outputStream->getData()[3])[1]);
```

- [x] Код вызова unpack читается тяжело. Сделай функцию с понятным именем и меньшим количеством параметов.

**Comment by alexey-malov** [comment]
По тестам для данной работы возникло ощущение, что они писались "просто для галочки". Рекомендую пообщаться с наставником, чтобы подсказал, как стоит писать тесты, чтобы они легче читались и было понятны проверяемые ими сценарии.
Рекомендуемое видео:
https://youtu.be/HvnQFishtDw

**Comment by ViacheslavTarasov** [comment]
Код распаковки символа из потока вынес в отдельный метод. Тесты с возможным бесконечным циклом переписал на тесты с конечным циклом. Постарался сделать код тестов более читаемыми. 

Также добавил  тесты метода isEof для DecryptInputStream. которые проверяют,  что метод isEof для DecryptInputStream должен возвращать true тогда и только тогда, когда декорированный поток возвращает true. Получается, что в тест проникают детали реализации.

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/tests/lab03/Sream/DecompressInputStreamTest.php#L22-L26
"ReadByteReturnsEmptyString" - ReadByte возвращает пустую строку

https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/tests/lab03/Sream/DecompressInputStreamTest.php#L28-L32
"testReadByteReturnsStringOneCharLong" - ReadByte возвращает строку длиной 1 символ

Из имен этих двух тестов не ясно, должна ли ReadByte возвращать пустую строку или же строку длиной один символ.

---

https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/tests/lab03/Sream/DecompressInputStreamTest.php#L43-L47
"testReadBlockReturnsEmptyString" - ReadBlock возвращает пустую строку

https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/tests/lab03/Sream/DecompressInputStreamTest.php#L49-L53
"testReadBlock" - проверяем ReadBlock

https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/tests/lab03/Sream/DecompressInputStreamTest.php#L55-L58
"testReadBlockFully" - читаем блок полностью

Если провалится тест testReadBlockFully, как понять, что именно сломалось?

https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/tests/lab03/Sream/DecompressInputStreamTest.php#L60-L63
"testReadBlockWhenLengthGreaterThanStringLength" - Читаем блок, когда длина больше, чем длина строки

Если провалится тест testReadBlockWhenLengthGreaterThanStringLength, как имя упавшего теста поможет понять, какой именно функционал тестируемого класса сломался?

- [ ] Имена этих и многих других тестов несут мало информации о том, что именно они тестируют. Тесты полезны тогда, когда они падают. Имя упавшего теста должно приносить в этой ситуации максимальную пользу. Хороший способ - стремиться именовать тесты как требования спецификации.
Когда тест называется  "размер возвращаемой readBlock строки не превышает размера упакованных данных" (testReadBlockReturnedStringSizeDoesNotExceedSizeOfCompressedData), разработчику будет достаточно имени теста, чтобы понять, какое требование спецификации было нарушено.

**Comment by alexey-malov** [comment]
Наилучший способ обеспечить такую структуру тестов - начать писать их до написания кода

**Comment by ViacheslavTarasov** [comment]
Исправил имена тестов в соответствии с форматом ИмяМетодаОжидаемоеПоведениеПриКакихУсловиях. Как я понял, такой шаблон именования позволяет описать требования спецификации достаточно полно и ближе к естественному языку. С  другой стороны становится сложно придумывать краткие и емкие наименования

**Comment by alexey-malov** [comment]
В некоторых тестовых фреймворках средства языка позволяют записывать тесты более читаемо. Например, JS фреймворк mocha:
```js
var assert = require('assert');
describe('Array', function() {
  describe('#indexOf()', function() {
    it('should return -1 when the value is not present', function() {
      assert.equal([1, 2, 3].indexOf(4), -1);
    });
  });
});
```
https://learn.javascript.ru/testing-mocha

В php тоже можно подобные штуки делать:
https://github.com/kahlan/kahlan

Еще набор php инструментов:
https://www.softwaretestingmagazine.com/tools/open-source-behavior-driven-development-bdd-tools-for-php/
