### ISSUE TITLE
Замечания по классу ShapeFactory

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#15]
- [x] Вспомогательный метод assertCount может быть сделан обычной функцией, так как ему не требуется иметь доступ к состоянию класса
- [x] Слово assert в имени assertCount может вводить в заблуждение при чтении. Традиционно assert-ы выполняются только в отладочной конфигурации (для отлова логических ошибок в приложении). Здесь же логика требует, чтобы назависимо от конфигурации приложения проверка выполнялась. Имя вроде `checkArraySize` подошло бы больше

**Comment by ViacheslavTarasov** [comment]
Переименовал и вынес функцию в отдельный namespace. 
На мой взгляд, приватный метод смотрелся уместнее, т.к. реализовывал поведение необходимое именно в этом классе - выброс определенного исключения при невыполнении условий

**Comment by alexey-malov** [comment]
В этом случае метод мог бы быть статическим
