### ISSUE TITLE
Интерфейсы и фабрики для цвета, пожалуй, будут излишними

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#16]
- [x] `ColorInterface`, пожалуй, является излишним. Во-первых, у него всего одна реализация. Во-вторых, от него не требуется полиморфное поведение. Обычный класс с getter-ами был бы достаточнен

- [x] Отдельная абстрактная фабрика для создания цветов тоже является избыточной

**Comment by ViacheslavTarasov** [comment]
Убрал ColorFactory и ColorFactoryInterface. Выделил в Color именованый конструктор createFromString
