### ISSUE TITLE
Замечания по фигурам из задания "Фабрика"

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#19]
- [ ] Интерфейс ShapeInterface, возможно, является излишним. Вместо него можно использовать абстрактный класс Shape.

В классе Shape метод draw(canvas) объявлен абстрактным (но это, на мой взгляд избыточно, так как достаточно того, что draw уже был объявлен в интерфейсе ShapeInterface, а в абстрактном классе Shape его просто можно было просто не упоминать

**Comment by ViacheslavTarasov** [comment]
Действительно, интерфейс и астрактный класс одновременно здесь неуместны. Интерфейс удалил, оставил абстрактный класс. 
Вообще осталось некоторое непонимание, когда интерфейс не нужен и достаточно конкретной реализации. Нередко вижу код, в котором интерфейс реализован одним классом

**Comment by alexey-malov** [comment]
Нет ничего плохого в том, что в программе у некоторого интерфейса может быть одна единственная реализация. Это позволяет избавить классы от взаимной зависимости друг от друга:
Класс A является клиентом класса B. Классу B в ходе работы нужно передавать классу A некоторую информацию (например, прогресс выполнения). Если оба класса будут знать друг о друге, это сделает их тесно связанными и нельзя будет ввести класс С, который бы тоже являлся клиентом класса B. Также нельзя будет протестировать работу класса B отдельно от класса A.
Решением проблемы будет введение интерфейса I, который использовался бы классом B для передачи информации своим клиентам. В этом случае класс A мог бы этот интерфейс сам реализовать. Также класс B можно было бы протестировать без класса A, подставив mock-реализацию интерфейса B.

**Comment by alexey-malov** [comment]
Абстрактные классы являются каркасами для построения конкретных классов на их основе, а также используются в ряде паттернов вроде "Шаблонного метода" или "Фабричный метод".
При помощи интерфейсов задаются протоколы для взаимодействия между объектами.

При зависимости от интерфейса нам совершенно не важно, какой класс будет его реализовывать, покуда реализация удовлетворяет условиям контракта, описанного в интерфейсе (предусловия и постусловия - см. принцип подстановки Барбары Лисков).

При зависимости от абстрактного класса посредством композиции или агрегации нам тоже должно быть не важно, какой из подклассов будет его реализовывать (принцип Барбары Лисков здесь тоже справедлив). Но абстрактный класс тоже содержит некоторую реализацию и связь с ним более сильная.

Как правило, классы моделируют сущности, и их имена часто являются именами существительными. Интерфейсы более абстрактны, они скорее говорят о том, какой должен быть объект. Поэтому интерфейсы могут именоваться при помощи прилагательных (Drawable, Executable) или абстрактных понятий (DataSource, Repository).
