### ISSUE TITLE
Замечания по реализации паттерна "Стратегия" в функциональном стиле.

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#2]
Под реализацией паттерна "Стратегия" в функциональном стиле подразумевалось, что вместо введения интерфейса `FlyBehavior` с единственным методом `Fly`, для реализации которого нужно создавать отдельный класс, можно ввести функцию, реализующую стратегию полёта.
Т.е. "Утка" так и останется классом, просто вместо интерфейсов стратегий будет хранить (и принимать) функции. 
У тебя же в программе объекты duck являются функциями.

**Comment by ViacheslavTarasov** [comment]
Исправил. Теперь SimUDuckFP\Duck принимает поведение в виде фукций

**Comment by alexey-malov** [comment]
ok
