### ISSUE TITLE
Проверку строки на null в php следует делать явно

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#20]
https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/Lab03/Stream/CompressOutputStream.php#L31-L33

- [ ] Если строка `$packed` будет содержать строку "0", то php приведёт ее к значению false, и байт не будет записан в декорированный поток вывода. Текущая реализация compressionService возвращает либо null либо строки из двух символов, поэтому эта ситуация здесь возникнуть не может, но я рекомендую выработать привычку явной проверки строк на null, чтобы в иной ситуации не попасть в ловушку из-за этой особенности php

**Comment by ViacheslavTarasov** [comment]
Исправил
