### ISSUE TITLE
Замечания по классу DocumentItems

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#22]
https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/lab05/Document/DocumentItems.php#L25-L28

- [x] Переименовать в getItemCount() (в английском языке главное существительное (count) ставится в конец, после зависимого (item))

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/lab05/Document/DocumentItems.php#L8-L10

- [ ] Здесь коллекция DocumentItems объявлена итератором, и в итоге отвечает за 2 задачи - хранение элементов и перемещение по ней. Можно сравнить с таблицей в БД, свойством которой является курсор, указывающий на текущий элемент. В БД итератор отделяется от самих данных и хранится в результате SELECT-запроса.
Здесь более уместным будет реализовать интерфейс IteratorAggregate

**Comment by ViacheslavTarasov** [comment]
Метод переименовал, реализацию коллекции поправил
