### ISSUE TITLE
Замечания по классу DocumentPrinter

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#23]
https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/lab05/Document/DocumentPrinter.php#L8-L21

- [x] У меня есть сомнения в правильности решения сделать документ свойством document printer-а. Представим, следующую функцию:
```php
function doSomethingWithPrinter(DocumentPrinter $printer) {
    что здесь можно сделать с $printer?
}
```
Какой аспект поведения DocumentPrinter-а позволяет называть его **Document**Printer-ом?
Метод doPrint без параметров? То есть получается такой класс одноразового использования сразу после создания.

Если же сделать DocumentInterface параметром метода print, то сразу всё встаёт на свои места
```php
class Foo {
    private $document;
    function doSomethingWithPrinter(DocumentPrinter $printer) {
        $documentPrinter->print($this->document);
    }
}
```

**Comment by ViacheslavTarasov** [comment]
Просчет осознал, код  поправил
