### ISSUE TITLE
Замечания по HtmlGenerationService

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#24]
https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/lab05/Service/HtmlGenerationService.php#L22-L25
https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/lab05/Service/HtmlGenerationService.php#L40-L42

- [x] При наличии спецсимволов html в заголовке или тексте параграфа можно сделать XSS-атаку. Нужно эскейпить html-сущности (в задании это сказано)

**Comment by alexey-malov** [comment]
- [ ] Сомнительным в текущей реализации видится выделение HtmlGenerationService в отдельную подсистему Service\ из Document\DocumentSavingService. HtmlGenerationService по-прежнему зависит от сущностей из Document. В итоге образовалась циклическая зависимость между Document\ и Service\

**Comment by ViacheslavTarasov** [comment]
Преобразование спецсимволов добавил.
Зависимость /Service от /Document устранил, реализовав передачу данных в HtmlGenerationService через DTO

**Comment by ViacheslavTarasov** [comment]
Предыдущее решение показалось избыточным. Перенес HtmlGenerationService  в Lab05\Document и убрал DTO
