### ISSUE TITLE
Замечания по History

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#25]
https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/lab05/Document/History.php#L8-L10

- [x] Константу MAX_COUNT, если она не используется в самом классе, можно убрать из класса History

**Comment by ViacheslavTarasov** [comment]
Убрал
