### ISSUE TITLE
Замечания по реализации меню

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#26]
https://github.com/ViacheslavTarasov/ood-labs/blob/aa3647c33ef6bebb9aa5ab2d6203b18eb59ff13b/lab05/Menu/MenuInterface.php#L6-L16

- [x] Пока не все методы меню имеет смысл выносить в интерфейс. В частности, run и addItem

**Comment by ViacheslavTarasov** [comment]
Методы run и addItem убрал из интерфейса

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/b1cfeae1b098378a51840c1768a7ae715c3fe36e/lab05/Menu/MenuItem.php#L12-L15

- [ ] Неверно указана аннотация у поля $command

**Comment by ViacheslavTarasov** [comment]
Исправил

**Comment by alexey-malov** [comment]
ok
