### ISSUE TITLE
Замечания по структуре namespace-ов в 5 лабе

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#27]
- [ ] Сейчас по namespace-ам распределены классы неудачно. Например, классы неймспейса меню знают о классах неймспейса документа, а AbstractCommand - о классах из неймспейса документа. И наоборот. В результате возникают циклические зависимости между модулями.

Примерно так:

- Menu\ - содержит классы для построения меню. Не имеют зависимостей
- History\ - классы для организации Undo/Redo. Не имеют зависимостей
- Document\ - классы модели документа. Зависят от History
- Document\Commands\ - команды, обеспечивающие undo/redo в документе. Зависят от Document\ и History\
- Service\ - сервисы, не зависят от других модулей
- App\ - слой приложения. Зависит от Document\
- App\Menu - команды, обеспечивающие работу меню\ Зависят от Document, Menu, Service

**Comment by ViacheslavTarasov** [comment]
Код по предложенной структуре реарганизовал. Правда не удалось избавится от зависимости Document от Service. Связано это с тем, что DocumentInterface предполагает  сохранение документа через метод save(). Вижу несколько решений:
1. Перенести сервисы в /Document
2.  В слое App извлечь данные из документа, сформировать DTO и передать в сервис сохранения. В этом случае DocumentInterface::save() будет не нужен
3. Объявить интерфейс сервиса сохранения в Document, а реализацию разместить в Service. В этом случае будет зависимость Service от Document 
4. Оставить как есть - зависимость Document от DTO из Service

**Comment by ViacheslavTarasov** [comment]
Оставил в Lab05\Service\ только FilesystemService, от которого есть зависимость в Lab05\Document\DocumentSavingService
