### ISSUE TITLE
Ослабить зависимость изображения и параграфа от класса History

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#29]
- [x] Изображению и параграфу не нужны все методы класса History. Им нужен лишь метод, позволяющий сохранить команду. Можно ввести интерфейс, который бы был реализован классом Document

**Comment by ViacheslavTarasov** [comment]
Интерфейс с соответствующим методом добавл. Для чего классу Document реализовывать этот интерфейс так и не понял

**Comment by alexey-malov** [comment]
Как правило, интерфейс должен обеспечить возможность взаимодействия классов модуля с внешним кодом (как, например, модуль меню объявляет интерфейс MenuCommandInterface, чтобы его клиенты могли создавать свои команды).
В твоем случае внутри модуля History\ объявлен интерфейс CommandExecutantInterface, который этим модулем не используется (хотя используется клиентскими модулями). В результате получается, модуль History делает предположения о том, как его классы будут использоваться другими модулями.
А если бы интерфейс CommandExecutantInterface был объявлен внутри модуля Document\, то его могли бы использовать классы изображения и параграфа, а документ выступал бы в роли адаптора, передавая в их конструкторы ссылку на самого себя. В методе addAndExecuteCommand он бы выполнял соответствующий вызов у своей history.

**Comment by ViacheslavTarasov** [comment]
Теперь стало понятно. Спасибо!
