### ISSUE TITLE
Можно вычисление среднего направления ветра упростить

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#3]
https://github.com/ViacheslavTarasov/ood-labs/blob/21a36578feab44f22cb522901f13de93a62ecebe/lab02/Common/WindDirectionStatistics.php#L26-L28

- [x] Нет нужды аккумулировать количество измерений и находить усреднённое значение суммы синусов и усреднённое значение суммы косинусов. atan2 при вычислении разделит сумму синусов на сумму косинусов. А если числитель и знаменатель дроби разделить или уможить на одно и то же число (количество измерений в нашем случае), то дробь не изменится

P.S. Просьба не закрывать issues и чекбоксы не проставлять. Я это сам делаю

**Comment by ViacheslavTarasov** [comment]
Да, надо было мне повнимательнее отнестись к функции atan2. Вычисление среднего направления ветра упростил.
