### ISSUE TITLE
Замечания по Rectangle (lab 6)

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#30]
https://github.com/ViacheslavTarasov/ood-labs/blob/4d2c4a173ea2354d9777bcda2a767f673ec0e61f/lab06/ShapeDrawingLib/Rectangle.php#L27-L39

- [x] - неудачные имена переменных  (x - координата не имеет высоты и top и bottom к ним не применимо),

**Comment by ViacheslavTarasov** [comment]
Убрал переменные для x, y кординат. Используются точки $this->topLeft и $this->bottomRight

translate.google.com:
точка "слева сверху" - "top left"
точка "справа снизу" - "bottom right"

**Comment by alexey-malov** [comment]
Как вариант, можно было ввести локальные переменные left, top, right и bottom.
С ними код читался бы проще.

**Comment by ViacheslavTarasov** [comment]
Исправил. Действительно, так нагляднее
