### ISSUE TITLE
Замечания по HexToRgbaConverter и тестам

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#31]
https://github.com/ViacheslavTarasov/ood-labs/blob/4d2c4a173ea2354d9777bcda2a767f673ec0e61f/lab06/ModernGraphicsLib/HexToRgbaConverter.php#L6-L9

- [x] Класс не имеет данных, но для его использования требуется создать его экземпляр.

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/4d2c4a173ea2354d9777bcda2a767f673ec0e61f/lab06/App/Adapter/ModernGraphicsRendererAdapter.php#L25-L33

- [ ] Лучше адаптеру не вызывать BeginDraw() в своем конструкторе. Лучше предоставить решение об этом вызове вызывающему коду

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/4d2c4a173ea2354d9777bcda2a767f673ec0e61f/tests/lab06/App/Adapter/ModernGraphicsRendererAdapterTest.php#L35-L42

- [ ] Почему проверяется вызов endDraw() при разрушении адаптера, если адаптер этого не делает? Закрывающий тэг draw выводится лишь потому, что в тесте никто не ссылается на modern graphics renderer

**Comment by alexey-malov** [comment]
- [ ] Имена тестов адаптера не должны включать в себя упоминания о том, что что-то будет выведено. Задача адаптера - преобразовывать вызовы  через реализуемый адаптером интерфейс к адаптируемому объекту. Внутри тестов проверки вывода останутся (потому как это единственный побочный эффект работы рендерера. А вот имена тестов должны звучать как спецификация адаптера, а не адаптируемого объекта:

- lineTo connects current point with new point
- moveTo changes current point without drawing a line
...

**Comment by alexey-malov** [comment]
- [ ] В тестах адаптера класса не стоит проверять методы, не относящиеся к целевому интерфейсу, вроде выбрасывания исключения при двойном вызове beginDraw - это не методы адаптера, а методы адаптируемого класса

**Comment by ViacheslavTarasov** [comment]
1. В классе HexToRgbaConverter сделал методы статическими, теперь класс используется без создания экземпляра

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/46f92d8b41c3ecc40dbf4d65448f73617d626f1d/tests/lab06/App/Adapter/ModernGraphicsRendererAdapterTest.php#L39-L43

- [ ] Имя теста (lineTo соединяет точку по умолчанию с новой точкой) не является требованием спецификации (это неверное требование, хотя и формально соответствует тому, что проверяет тест). А вот "Точка по умолчанию имеет координаты 0,0" - является.

**Comment by ViacheslavTarasov** [comment]
Исправил имя теста на предложенное  для обоих адаптеров
