### ISSUE TITLE
Замечания по диаграммам адаптера

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#32]
![image](https://user-images.githubusercontent.com/6040682/76116974-f6301e00-5ffb-11ea-9ace-1523952718a6.png)

- [x] Перепутаны направления в связях вида Композиция и Агрегация

**Comment by alexey-malov** [comment]
![image](https://user-images.githubusercontent.com/6040682/76117194-6fc80c00-5ffc-11ea-8553-8fd9392cca07.png)

- [ ] Перепутаны направления в связях Композиция и Агрегация

**Comment by ViacheslavTarasov** [comment]
Направления в связях исправил. Лишний файл убрал

**Comment by alexey-malov** [comment]
![image](https://user-images.githubusercontent.com/6040682/76171320-c1a69880-619a-11ea-9ff7-5960ce0bc3a3.png)

- [ ] Отношение реализации интерфейса обозначается пунктирной линией, а не сплошной (она используется для отношения наследования)

**Comment by ViacheslavTarasov** [comment]
Исправил. Изначально была пунктирная линия, пока не разукрасил
