### ISSUE TITLE
Замечания по реализации групповых стилей

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#33]
https://github.com/ViacheslavTarasov/ood-labs/blob/4d2c4a173ea2354d9777bcda2a767f673ec0e61f/lab07/Shape/Style/GroupFillStyle.php#L8-L12

- [x] Стиль не должен ничего знать про фигуры. Составной стиль должен в конструкторе принимать интерфейс, позволяющий перебирать стили. Этот интерфейс должна реализовывать группа. Сейчас если стили выделить в отдельный модуль, то будет циклическая связь между модулем стилей и фигур. Мы же обсуждали это на встрече,

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/46f92d8b41c3ecc40dbf4d65448f73617d626f1d/lab07/Style/GroupFillStyle.php#L18-L23

- [ ] Когда у части фигур стиль обводки/заливки включен, а у другой части выключен, будет возвращаться значение false. Тут лучше тоже nullable-значение возвращать, где null обозначает, что значение свойства смешанное

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/46f92d8b41c3ecc40dbf4d65448f73617d626f1d/lab07/Style/GroupFillStyle.php#L48-L70

- [ ] Запутанными выглядит "жонглирование"  значением переменной $color - то ей последовательно null присваивают, то цвет из текущего стиля, то снова null.

**Comment by ViacheslavTarasov** [comment]
- метод `isEnabled(): ?bool` переделал для `GroupFillStyle` и `GroupLineStyle`

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/lab07/Style/GroupLineStyle.php#L22-L29

- [ ] В строке 26 лучше использовать значение false, а не null

**Comment by ViacheslavTarasov** [comment]
Исправил
