### ISSUE TITLE
Выделить стили в отдельный модуль

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#34]
- [x] Убрать стили из модуля Shapes.

- [x] Убрать циклические связи между модулем Shapes и Style за счёт инверсии зависимостей

**Comment by ViacheslavTarasov** [comment]
- cтили вынес из `Shapes`
- зависимость `Style` от `Shapes` устранил

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/lab07/Style/FillStyleIterable.php#L6
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/lab07/Style/LineStyleIterable.php#L6

- [ ] По PSR имена интерфейсов должны заканчиваться на Interface

**Comment by ViacheslavTarasov** [comment]
Исправил
