### ISSUE TITLE
Замечания по реализации фигур в 7 лабе

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#35]
https://github.com/ViacheslavTarasov/ood-labs/blob/46f92d8b41c3ecc40dbf4d65448f73617d626f1d/lab07/Shape/Ellipse.php#L10-L23

https://github.com/ViacheslavTarasov/ood-labs/blob/46f92d8b41c3ecc40dbf4d65448f73617d626f1d/lab07/Shape/Ellipse.php#L50-L70

- [x] Хранение в эллипсе зависимых данных:  (фрейма и центра с шириной и высотой) усложняет его реализацию - приходится следить за тем, чтобы данные все время были согласованы. Если быстродействие не является превалирующим фактором, то лучше такого усложнения избежать.

Если же хочется сделать фрейм производным свойством, то  лучше его вычислять и кешировать в getFrame(), а в setFrame() сбрасывать в null. А то получается половинчатое решение

**Comment by alexey-malov** [comment]
- [ ] Зачем создавать экземпляр PointTransformationService, если у него нет состояния?

**Comment by ViacheslavTarasov** [comment]
- от хранения фрейма в эллипсе и прямоугольнике избавился
- сделал метод статическим - `PointTransformationService::transform()`. Изначально задумывал явно передвать экземпляр в конструктор
