### ISSUE TITLE
Замечания по тестам 7 лабораторной работы

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#36]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/tests/lab07/Shape/GroupShapesTest.php#L52-L56

- [x] Лучше бросать исключение при невалидном индексе

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/tests/lab07/Shape/GroupShapesTest.php#L148-L155

- [ ] Название теста "getFrame() возвращает фрейм добавленной фигуры" не соответствует требованиям задания. Такое происходит лишь в том случае, когда фигур в группе нет (но из имени теста это не следует).

**Comment by alexey-malov** [comment]
- [ ] Нет теста, проверяющего resize пустой группы

**Comment by alexey-malov** [comment]
- [ ] Нет теста, проверяющего, что наличие внутри группы фигур с null-фреймом не оказывает влияния на итоговый фрейм группы

**Comment by ViacheslavTarasov** [comment]
- выброс исключения при невалидном индексе реализовал, тест поправил
- тест `testGetFrameReturnsSameFrameAsAddedShape` убрал
- указанные тесты добавил
