### ISSUE TITLE
Замечания по реализации групповой фигуры

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#37]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/tests/lab07/Shape/GroupShapesTest.php#L74-L84
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/lab07/Shape/GroupShapes.php#L58-L64

- [x] Удаление фигуры должно не просто уменьшать количество фигур, но еще и сдвигать фигуры, следующие за удаляемой на ее место. Иначе получив группу, у которой getShapeCount() возвращает 10, нельзя быть уверенным в том, что фигуры размещаются с индексами от 0 до 9 (то есть в массиве не содержатся "дырки")

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/tests/lab07/Shape/GroupShapesTest.php#L117-L123

- [ ] Оставшиеся фигуры после удаления должны сдвигаться на место удаляемой фигуры, поэтому требование этого теста сформулировано некорректно

**Comment by ViacheslavTarasov** [comment]
Сдвиг фигур при удалении реализовал, в тесте `testRemoveAtIndexDoesNotRemoveOtherShapesAndNextShapesAreShifted` это проверяется
