### ISSUE TITLE
Замечания по классу Slide

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#38]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/lab07/Slide/Slide.php#L64-L70

- [x] Удаление фигур не должно оставлять "дыр" внутри массива фигур

**Comment by ViacheslavTarasov** [comment]
Исправил
