### ISSUE TITLE
Замечания по тестам GumballMachine

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#39]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/tests/lab08/GumballMachine/State/HasQuarterStateTest.php#L23-L27

- [x] Имя теста не звучит как требование спецификации.

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/tests/lab08/GumballMachine/State/NoQuarterStateTest.php#L30-L34

- [ ] testEjectQuarterNotReturnsQuarter -> testQuarterCantBeEjected

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/tests/lab08/GumballMachine/State/NoQuarterStateTest.php#L36-L40

- [ ] testTurnCrankSaysNotQuarter -> testTurningCrankHasNoEffect

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/tests/lab08/GumballMachine/State/NoQuarterStateTest.php#L42-L46

- [ ] testNotDispensed -> testDispenseIsProhibited

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/tests/lab08/GumballMachine/State/SoldStateTest.php#L23-L27

- [ ] testNotInsertedQuarter -> testQuarterInsertionIsNotAllowed

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/tests/lab08/GumballMachine/State/SoldStateTest.php#L29-L33

- [ ] testNotEjectedQuarter -> testQuarterCantBeEjected

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/tests/lab08/GumballMachine/State/SoldStateTest.php#L35-L39

- [ ] testTurnCrankDoesNotReleaseGumballTwice -> testTurningCrankDoesNotReleaseGumball. Слово twice здесь не подходит, потому что конкретно в этом состоянии ты не проверяешь двойное дергание ручки

**Comment by alexey-malov** [comment]
https://github.com/ViacheslavTarasov/ood-labs/blob/e11cc567b19714c0b2c2038f8f74679aaa3f0bb2/tests/lab08/GumballMachine/State/SoldStateTest.php#L47-L52

- [ ] testDispenseSetsSoldOutStateWhenSoldLastGumball -> testDispenseSetsSoldOutStateAfterSellingLastGumball

**Comment by ViacheslavTarasov** [comment]
Тесты переименовал
