### ISSUE TITLE
ObserversStorage лучше не наследовать от SplObjectStorage

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#4]
- [x] Наследуя ObserversStorage от SplObjectStorage мы "сообщаем", что ObserversStorage является частный случаем SplObjectStorage и что с ним можно работь через "интерфейс" базового класса (используя его набор публичных методов). Наследование создаёт отношение "является" (is a): Cat is an animal, Button is an UI control, Circle is a shape.
Вообще, наследование от конкретного (т.е. небстрактного) класса часто свидетельствует о неверном использовании наследования, особенно если класс-наследник не переопределяет реализацию методов класса-родителя. В этом случае будет более правильным композиция или агрегация. Наследуют не ради повторного использования кода, а для того, чтобы можно было работать с реализацией наследников через интерфейс родителя.

**Comment by ViacheslavTarasov** [comment]
Реализовал объект PriorityStorage, вместо ObserversStorage. В ObserversStorage (он более не нужен) убрал наследование и применил композицию
