### ISSUE TITLE
Утранить циклические зависимости между модулями GumballMachine\Context и GumballMachine\State

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#40]
- [x] Сейчас классы состояний и контекста зависят namespace-ов друг друга взаимно. Нужно перенести один из интерфейсов из одного namespace-а в другой, чтобы циклической зависимости не было.

**Comment by ViacheslavTarasov** [comment]
Из PrivateGumballMachineInterface выделил StateSettableInterface, который разместил в State. Теперь State не зависит от Context

**Comment by ViacheslavTarasov** [comment]
Перенес PrivateGumballMachineInterface в State
