### ISSUE TITLE
Выпилить лишние методы из интерфейса PrivateGumballMachineInterface

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#41]
- [x] Если этот интерфейс служит для использования состояниями, то должен содержать только методы, необходимые состояниям. Если же этот интерфейс служит для использования Frontend-ом gumball machine, то должен содержать только методы, необходимые gumball machine (либо GumballMachine должна использовать его через класс). В общем, примени принцип разделения интерфейса

**Comment by ViacheslavTarasov** [comment]
Из PrivateGumballMachineInterface выделил StateSettableInterface, который разместил в State

**Comment by ViacheslavTarasov** [comment]
Методы  insertQuarter(), ejectQuarter(), turnCrank() в PrivateGumballMachineInterface убрал из PrivateGumballMachineInterface. Теперь класс PrivateGumballMachine реализует интерфейсы GumballMachineInterface и PrivateGumballMachineInterface
