### ISSUE TITLE
Есть сомнения насчёт необходимости выделения интерфейса DisplayInterface

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#5]
- [x] Мне не удалось найти объектов, которые бы использовали интерфейс DisplayInterface. Как правило, следует вводить интерфейсы, когда есть клиенты, их использующие.

**Comment by ViacheslavTarasov** [comment]
Действительно, нет клиентов, которые  используют DisplayInterface. Убрал.
