### ISSUE TITLE
Улучшить реализацию подписки на интересующие события

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#6]
- [x] Вместо интерфейса наблюдателя с методом update при подписке на интересующие события лучше подходят замыкания,. Тогда каждое событие об изменении будет направляться в отдельную функцию без необходимости при помощи if обработчику определять характер произошедших изменений.
Я не знаю, можно ли в php сравнивать объекты замыканий друг с другом (чтобы потом можно было отписаться). Но даже если язык такого не позволяет, простейшим решением было бы возвращать токен (достаточно будет целого числа, генерируемого автоинкрементом), чтобы его потом можно было бы передать в removeObserver

**Comment by ViacheslavTarasov** [comment]
Переделал реализацию на замыкания
