### ISSUE TITLE
Будет ли ожидаемым образом работать повторное добавление одного и того же объекта-наблюдателя (с другим приоритетом)

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#8]
- [x] Я не очень в курсе, как в php работает SplObjectStorage в случае, когда мы в attach передаём несколько раз один и тот же объект с, возможно, разными data. Будет ли ожидаемым поведение программы?

**Comment by ViacheslavTarasov** [comment]
Если в attach передавать один и тот же объект, то он будет добавлен только один раз. Соответственно при уведомлении наблюдателей, конкретный экземпляр наблюдателя будет уведомлен один раз, независимо от того, что его регистрировали несколько раз.
