### ISSUE TITLE
Реализация базового класса Beverage, возможно, не очень удачная

### ISSUE THREAD

**Issue by alexey-malov** [ViacheslavTarasov/ood-labs#9]
https://github.com/ViacheslavTarasov/ood-labs/blob/71293e7148583cd3bd7807e5b8922ab3063122d0/Lab03/Beverage/Beverage.php#L5-L42

- [x] Поле size в классе объявлено защищённым, хотя не используется в наследниках. Данные, как правило, лучше объявлять приватными, чтобы ограничить доступ к ним только самим классом.

- [x] Судя по реализации класс стоило бы назвать как-то вроде SizableBeverage, MultiSizeBeverage или SizedBeverage

- [ ] Класс полагается на размер, передаваемый в конструктор и хранит его, но предоставление "прайс-листа" и названия напитка всякий раз делегирует классам-наследникам. Возможно, лучше было бы, если бы класс принимал в конструктор размер, название и прайс-лист, а наследники в своих конструкторах передавали бы конструктору базового класса эти данные.

**Comment by ViacheslavTarasov** [comment]
Поле size сделал private. Класс переименовал и переписал, чтобы конструктор принимал  размер, название и прайс-лист
